name: Cypress Tests

on: [push]

jobs:

  test-material-ui-viewer:
    name: ITK Viewer Material UI Tests
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.13.2-chrome100-ff98

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Test with Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start

      - name: Test with Firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
